### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by robmcguinness** [jdhornsby/terraform-get-plan#1]
- use `fs` promise api https://nodejs.org/api/fs.html#fs_fspromises_writefile_file_data_options.
- switch to use https://github.com/sindresorhus/execa instead of `child_process` directly. fyi there is also if need use https://nodejs.org/api/util.html#util_util_promisify_original to turn callback function to promise (but I would still use `execa`)

I think both those suggestions would remove the need for Bluebird.

**Comment by jdhornsby** [comment]
Bluebird removed in 0.0.2. Thanks!
